# lsi: false
# safe: true
# følgende source declaration giver en fejl, hvis jeg server lokalt
# `realpath': No such file or directory @ realpath_rec - /home/velle/Desktop/osaawebsite/https: (Errno::ENOENT)
#source: "https://github.com/velle/osaawebsite"
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge


url: "https://osaa.dk" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "Open Space Aarhus" # the name of your site, e.g. ACME Corp.
exclude: [gems, node_modules, vendor, .idea]
plugins:
  - jekyll-paginate
  - jekull-sitemap
sass:
    load_paths:
        - _sass
        # - node_modules
        - 3rd_party_code
paginate: 10
paginate_path: "/news/page:num/"
theme: null
